### ISSUE TITLE
◈ Empty args assigned, this is an internal Netlify Dev bug, please report your settings and scripts so we can improve

### ISSUE THREAD

**Issue by lpatmo** [netlify/netlify-faunadb-example#26]
## New Post:

Problem:
![image](https://user-images.githubusercontent.com/4512699/91117747-3b94e600-e644-11ea-9bea-e31a096296ec.png)

Steps to recreate:
1. Deployed by clicking on the button
2. Create a new database on FaunaDB
3. Clone the repo created from deploying
4. npm install
5. npm audit fix
6. Ran $ export FAUNADB_SERVER_SECRET=[KEY]
7. npm run bootstrap

Running `npm run bootstrap` caused this error:
![image](https://user-images.githubusercontent.com/4512699/91117778-510a1000-e644-11ea-99ef-b5c004a66523.png)

So I ran `netlify link`. 

That went well, but running `npm start` next caused the same error:
![image](https://user-images.githubusercontent.com/4512699/91118148-2b313b00-e645-11ea-90f4-052a99d418f7.png)
```
> netlify-fauna@0.1.0 start /Users/lpnotes/Desktop/projects/bc
> netlify dev

◈ Netlify Dev ◈
◈ Injected addon env var:  FAUNADB_ADMIN_SECRET
◈ Injected addon env var:  FAUNADB_CLIENT_SECRET
◈ Empty args assigned, this is an internal Netlify Dev bug, please report your settings and scripts so we can improve
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! netlify-fauna@0.1.0 start: `netlify dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the netlify-fauna@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lpnotes/.npm/_logs/2020-08-25T02_53_25_800Z-debug.log
```

## The full debug log:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/12.9.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.10.3
3 info using node@v12.9.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle netlify-fauna@0.1.0~prestart: netlify-fauna@0.1.0
6 info lifecycle netlify-fauna@0.1.0~start: netlify-fauna@0.1.0
7 verbose lifecycle netlify-fauna@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle netlify-fauna@0.1.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/lpnotes/Desktop/projects/bc/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin
9 verbose lifecycle netlify-fauna@0.1.0~start: CWD: /Users/lpnotes/Desktop/projects/bc
10 silly lifecycle netlify-fauna@0.1.0~start: Args: [ '-c', 'netlify dev' ]
11 silly lifecycle netlify-fauna@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle netlify-fauna@0.1.0~start: Failed to exec start script
13 verbose stack Error: netlify-fauna@0.1.0 start: `netlify dev`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:326:16)
13 verbose stack     at EventEmitter.emit (events.js:209:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:209:13)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid netlify-fauna@0.1.0
15 verbose cwd /Users/lpnotes/Desktop/projects/bc
16 verbose Darwin 18.7.0
17 verbose argv "/usr/local/Cellar/node/12.9.1/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v12.9.1
19 verbose npm  v6.10.3
20 error code ELIFECYCLE
21 error errno 1
22 error netlify-fauna@0.1.0 start: `netlify dev`
22 error Exit status 1
23 error Failed at the netlify-fauna@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

## Old post:
After clicking on the button to deploy this to Netlify and creating the FaunaDB key, we were getting the following error:

![image](https://user-images.githubusercontent.com/4512699/90990119-a9adb000-e553-11ea-97e5-32bc584f4c3d.png)

Can I add to the README.md the instruction to install the netlify CLI? https://docs.netlify.com/cli/get-started/

**Comment by lpatmo** [comment]
Update: getting this error: 

![image](https://user-images.githubusercontent.com/4512699/90990226-8800f880-e554-11ea-8585-afb652fa6cc7.png)

**Comment by hoop71** [comment]
I am getting the same error but after installation and on `npm start`

![image](https://user-images.githubusercontent.com/25015764/92267534-08e9b980-ee9e-11ea-874b-95b63647b981.png)


```0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/[name]/.nvm/versions/node/v13.8.0/bin/node',
1 verbose cli   '/Users/[name]/.nvm/versions/node/v13.8.0/bin/npm',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.13.6
3 info using node@v13.8.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle netlify-fauna@0.1.0~prestart: netlify-fauna@0.1.0
6 info lifecycle netlify-fauna@0.1.0~start: netlify-fauna@0.1.0
7 verbose lifecycle netlify-fauna@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle netlify-fauna@0.1.0~start: PATH: /Users/[name]/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/[name]/code/fun/wanna-hit/node_modules/.bin:/Users/[name]/.nvm/versions/node/v13.8.0/bin:/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/opt/sphinx-doc/bin
9 verbose lifecycle netlify-fauna@0.1.0~start: CWD: /Users/[name]/code/fun/wanna-hit
10 silly lifecycle netlify-fauna@0.1.0~start: Args: [ '-c', 'netlify dev' ]
11 silly lifecycle netlify-fauna@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle netlify-fauna@0.1.0~start: Failed to exec start script
13 verbose stack Error: netlify-fauna@0.1.0 start: `netlify dev`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/[name]/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:321:20)
13 verbose stack     at ChildProcess.<anonymous> (/Users/[name]/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:321:20)
13 verbose stack     at maybeClose (internal/child_process.js:1026:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid netlify-fauna@0.1.0
15 verbose cwd /Users/[name]/code/fun/wanna-hit
16 verbose Darwin 19.6.0
17 verbose argv "/Users/[name]/.nvm/versions/node/v13.8.0/bin/node" "/Users/[name]/.nvm/versions/node/v13.8.0/bin/npm" "start"
18 verbose node v13.8.0
19 verbose npm  v6.13.6
20 error code ELIFECYCLE
21 error errno 1
22 error netlify-fauna@0.1.0 start: `netlify dev`
22 error Exit status 1
23 error Failed at the netlify-fauna@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by av1nash** [comment]
Getting same error message.
c:\Workplace\DevOps\netlify-faunadb-example>npm start

> netlify-fauna@0.1.0 start c:\Workplace\DevOps\netlify-faunadb-example
> netlify dev

◈ Netlify Dev ◈
◈ Empty args assigned, this is an internal Netlify Dev bug, please report your settings and scripts so we can improve
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! netlify-fauna@0.1.0 start: `netlify dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the netlify-fauna@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by domnantas** [comment]
I had the same problem. Making the following changes fixed the issue:

```diff
// package.json

   "scripts": {
     "bootstrap": "netlify dev:exec node ./scripts/bootstrap-fauna-database.js",
     "docs": "md-magic --path '**/*.md' --ignore 'node_modules'",
-    "start": "netlify dev",
+    "dev": "netlify dev",
+    "start": "react-scripts start",
     "prebuild": "echo 'setup faunaDB' && npm run bootstrap",
     "build": "react-scripts build"
   },
```

```diff
// netlify.toml
 
 [dev]
   # Local dev command. A.k.a npm start
-  command = "react-scripts start"
+  command = "npm start"
```

**Comment by ctjlewis** [comment]
It seems like the project cannot run as-is due to the CLI detecting the `netlify dev` calls and throwing an error. The CLI logic is correct, and @domnantas provided the appropriate fix to prevent the CLI from attempting to recursively call itself.

See also: https://github.com/netlify/cli/pull/1798

**Comment by stevenfowler16** [comment]
Any update on this? I can't get this to work. Receiving the same error

**Comment by stevenfowler16** [comment]
Interestingly enough I updated faunadb and then the above fixes started working.
