### ISSUE TITLE
Error: Cannot find module 'faunadb'

### ISSUE THREAD

**Issue by AndrewZamora** [netlify/netlify-faunadb-example#3]
Thank you for the tutorial. 

I got stuck when I ran `npm run bootstrap`. This error showed up in the terminal:
```
> node ./scripts/bootstrap-fauna-database.js

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'faunadb'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\Andrew\Documents\webDev\netlify-db-example\scripts\bootstrap-fauna-database.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! netlify-db-example@0.1.0 bootstrap: `node ./scripts/bootstrap-fauna-database.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the netlify-db-example@0.1.0 bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
Is there something I overlooked in the tutorial?

**Comment by sw-yx** [comment]
did you run `npm install`? is there a `faunadb` folder in your `node_modules`?

**Comment by sw-yx** [comment]
ohh i see. yes, scroll up and start from "Setup & Run Locally"

**Comment by tinymachine** [comment]
I really appreciate your putting this tutorial together @DavidWells and @sw-yx, but, FWIW, I'm finding it confusing as well. Starting at the [Tutorial](https://github.com/netlify/netlify-faunadb-example/blob/271721bbc0f1ad7980824a896e000be510763369/README.md#tutorial) header in the readme, it looks like it's walking you step by step through the setup process (and assuming you have not already cloned the repo). I think this mostly works, except it should also include a step to run `npm install faunadb --save` before running `npm run bootstrap`.

**Comment by sw-yx** [comment]
ok. added

**Comment by tinymachine** [comment]
Thanks, @sw-yx; I noticed, though, that the tutorial already includes a separate step where you install faunadb (substep 4 under "[3. Create a function > Setting up functions for local development](https://github.com/netlify/netlify-faunadb-example/blob/641d3e3973264159c68797df482255d9969dc096/README.md#setting-up-functions-for-local-development)". 

A couple of additional concerns: 

- Again under "[3. Create a function > Setting up functions for local development](https://github.com/netlify/netlify-faunadb-example/blob/641d3e3973264159c68797df482255d9969dc096/README.md#setting-up-functions-for-local-development)", where it says "Your `package.json` should look like...", that doesn't match the [current `package.json`](https://github.com/netlify/netlify-faunadb-example/blob/641d3e3973264159c68797df482255d9969dc096/package.json) in this repo: there's no `proxy` field in the actual pkg, but there is in the readme version. I'm confused about how the repo proxies the locally served functions, and it's weird to have this disconnect.

- In step 4 of the tutorial ("[4. Connect the function to the frontend app](https://github.com/netlify/netlify-faunadb-example/blob/641d3e3973264159c68797df482255d9969dc096/README.md#4-connect-the-function-to-the-frontend-app)"), it's not indicated where you should put that front-end code (though there is a reference to the `/src` folder.)

- When I clone the repo, install, and run, the app seems to be working, but I'm seeing warnings in my console when I do CRUD operations:

```bash
Request from ::ffff:127.0.0.1: POST /todos-create
Function `todo-create` invoked { title: 'Complete tutorial', completed: false }
success { ref: Ref(Class("todos"), "232907278267712002"),
  ts: 1558376539460000,
  data: { title: 'Complete tutorial', completed: false } }
Response with status 200 in 358 ms.
(node:46618) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'statusCode' of undefined
    at callback ([...]/netlify-faunadb-example/node_modules/netlify-lambda/lib/serve.js:35:42)
    at [...]/netlify-faunadb-example/node_modules/netlify-lambda/lib/serve.js:67:7
    at [...]/netlify-faunadb-example/functions-build/todos-create.js:20:2972
    at T ([...]/netlify-faunadb-example/functions-build/todos-create.js:20:3006)
    at A ([...]/netlify-faunadb-example/functions-build/todos-create.js:20:2827)
    at m ([...]/netlify-faunadb-example/functions-build/todos-create.js:20:728)
    at process._tickCallback (internal/process/next_tick.js:61:11)
(node:46618) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```
FWIW, the version I deployed directly to Netlify does not show these same warnings in the Functions logs, e.g.:

```bash
3:55:26 PM: todos-create invoked
3:55:26 PM: Function `todo-create` invoked { title: 'Check if there are errors in direct-to-Netlify version',
  completed: false }
3:55:27 PM: success { ref: Ref(Class("todos"), "232924462000898562"),
  ts: 1558392927140000,
  data: 
   { title: 'Check if there are errors in direct-to-Netlify version',
     completed: false } }
```

- Even though I got the cloned repo installed and working, and the deployed-directly-to-Netlify ("TLDR") version working, the Fauna dashboard is still showing the "Create your first database" message, and there doesn't appear to be any way for me to access the created db through Fauna's admin interface. The data *is* being stored to some db in Fauna, because my created to-dos are persisting across sessions, etc. Not sure if this is a bug with Fauna?

  <img width="400" alt="Screen Shot 2019-05-20 at 3 25 40 PM" src="https://user-images.githubusercontent.com/171986/58056450-f830fb00-7b15-11e9-92cd-846a418e52be.png">

I am grateful for the effort put forth in writing this tutorial, but for me at least there a lot that's preventing this from being as easy to follow as I think was intended.

**Comment by sw-yx** [comment]
re: 4 there is no bug, you just need to claim your database created using the secrets given in your environment variables (you can run netlify dev:exec echo $FAUNADB_SERVER_SECRET or something like that)

re the rest, these are probably tutorial updates we need to make. i am going to reopen this issue to keep it in mind.

**Comment by tinymachine** [comment]
Thanks so much for replying so quickly, @sw-yx, and for explaining the claiming issue. (As you probably know, the readme doesn't mention this, and actually it specifically says that you *should* see the db created in your FaunaDB account.)

I look forward to the updated version of this tutorial -- thanks again for your help.

**Comment by tinymachine** [comment]
Again, in case it's helpful to others, I was able to connect the todo app to a Fauna database that can be viewed from Fauna's dashboard. 

To do so, I followed these steps: 

1. Create a new database in the [FaunaDB dashboard](https://dashboard.fauna.com) by clicking the "New Database" button.
2. Somewhat counterintuitively, return to the Console Home and click "Manage Keys" (instead of accessing the "Keys" section from within the database view, which only lets you generate keys for child databases).
3. Click "New Child DB Key", then create a new key for your new database.
4. Copy the generated secret key, then use that key when Netlify prompts you for it after clicking the [Deploy to Netlify](https://app.netlify.com/start/deploy?repository=https://github.com/netlify/netlify-faunadb-example) button.

Now when you create to-dos in the deployed app, you can view them from your database view in the Fauna dashboard.

**Comment by sw-yx** [comment]
we do need to make this claiming process easier. working on it with Fauna.

**Comment by tinymachine** [comment]
Hi @sw-yx -- for what it's worth, for my needs, manually creating the db in the Fauna console is totally fine; the programmatic bootstrapping process isn't necessary for me. Out of curiosity, what is the use-case for programmatic bootstrapping? Is the idea that an app could set up separate databases for each registered user or something? (That seems unlikely...) Thanks for any details you can provide, and thanks again for sharing this repo!

**Comment by sw-yx** [comment]
the idea is simply to do as much as possible with one command! :) so for example in [netlify functions:create](https://github.com/netlify/netlify-dev-plugin/#netlify-functions) we let you scaffold out a function that interacts with a faunadb backend, AND set up a fauna instance for you all in one go. https://github.com/netlify/netlify-dev-plugin/tree/master/src/functions-templates/js/fauna-graphql

**Comment by tinymachine** [comment]
Thanks for explaining! (I was missing that bootstrapping includes actually creating the indexes and schema, etc. -- not just programmatically creating the db itself. I'm new to all this!)
